--- #YAML:1.0
name:               Statistics-Basic
version:            1.6602
abstract:           ~
author:  []
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Number::Format:  1.42
    perl:            5.006
    Scalar::Util:    0
resources:
    repository:  http://github.com/jettero/statistics--basic
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - stats
    - statistics
    - mean
    - average
    - correlation
